### ISSUE TITLE
Page Navigation

### ISSUE THREAD

**Issue by tjmareng** [tjmareng/Blendr#20]
Implement the navigation between pages when the corresponding buttons are clicked.

**Time Estimate**
2 days

**Acceptance Criteria**
GIVEN: I am a user
WHEN: I want to direct to another page on the application
THEN: There is an easy and accurate way for me to get there (to the page)

Parts:
- [ ] Edit Profile Page
- [ ] Home/Hub
- [ ] Login Screen
- [ ] Registration

**Comment by aciesla4** [comment]
aciesla4 is Ann the scrum master
